clusterName: homecluster
talosVersion: v1.9.3
endpoint: https://192.168.1.52:6443
allowSchedulingOnMasters: true
nodes:
  - hostname: node1
    ipAddress: 192.168.1.52
    installDisk: /dev/mmcblk0
    controlPlane: true
  - hostname: node2
    ipAddress: 192.168.1.44
    installDisk: /dev/mmcblk0
    controlPlane: false
  - hostname: node3
    ipAddress: 192.168.1.108
    installDisk: /dev/mmcblk0
    controlPlane: false
